# Generated by Django 5.2.13 on 2026-04-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('seats_pattern', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('registration_deadline', models.DateTimeField()),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('number_of_visitors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('status_changed_at', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.place')),
            ],
            options={
                'ordering': ('event_time', 'id'),
            },
        ),
    ]
