# Generated by Django 5.2.13 on 2026-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('published', 'Published')], db_index=True, max_length=64),
        ),
    ]
