# Generated by Django 5.2.13 on 2026-04-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='running', max_length=32)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='idle', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
